### ISSUE TITLE
Amazingly useful

### ISSUE THREAD

**Issue by mario0318** [zehuanli/Google-Voice-Mark-Read#1]
First off, what a fantastic plugin this is. A total time saver of immense proportion which finally puts a stop to the annoying need of opening the app/conversation to mark as read. Google can be highly innovative and intuitive, but man can they really settle for some design choices that make your head blow up. Anyway. Thank you! 

So, This isn't so much an issue but more of a "feature" request but not even that. Seeing how you mentioned in the latest release that you improved searching of objects which should be compatible with future GV versions for a while led me to ask how future proof can this be made, outside of course of a complete revamp if Google goes that way. 

I'm assuming there is no easy way to implement this mod as a feature if Google ever decided to remove the android.car.EXTENSIONS bundle, right? Otherwise we'd be dealing with having to rewrite some major parts of GV app to add it? I'm very much a noob with xposed mod developing or Android for that matter. So I'm genuinely curious because this mods code is absurdly simple taking a glance at it, but I could not tell you how to even begin looking for what bundles or what hooks to which class and parameters. Not trying to get a coding lecture out of you btw lol. Sorry for lengthy post.

**Comment by zehuanli** [comment]
Hi @mario0318,

Thank you for the post and I'm really happy to know that this tiny module worked for you!

The implementation of this module is stupidly simple - it hooks one of the GV methods that creates the notification, and adds the "Mark as Read" action to it. Just as you mentioned, it currently uses the `android.car.EXTENSIONS` bundle which is bound to be created by GV when the message is created.

I haven't dig into other codes of GV to see how it actually deals with this bundle, but by its name and the fact that you can "mark read" a message with Android Auto by playing the notification on your car, I believe this bundle is somehow sent to Android Auto for marking one message as read. On the other hand, Google may not simply remove this bundle unless there's a change of the interaction between GV and Android Auto, although this may happen at any time.

If the `android.car.EXTENSIONS` is removed, we don't have to rewrite a major part of GV app (depending how you define "major" I guess), but we do need to write some codes to find and utilize the method(s) in GV that can mark a message as read. Those method(s) definitely exist since GV has to be able to mark a message as read. However, the more complicated our logic is, the harder we can make it survive future GV updates, or otherwise we'll have to decompile the GV package, find the method(s) and update our module every time.

The reason that the latest update of this module may hopefully survive some GV updates is that the methods `putParcelable` and `setRemoteInputHistory` that we hook belong to Android but not GV, so we don't need to worry about the changes of the obfuscated GV class names. These methods are only used once in GV, so we don't need to check and deal with unrelated invocations on these methods.

For finding the methods to hook and objects (bundles) to utilize, I simply started with searching for anything related to Android Notification as well as actions on the messages, and luckily got what I need. I'm not a pro and don't even have much experience on reverse engineering, and there must be some better and systematic way to find what you want out of a large and obfuscated package.

Of course, the best thing I would hope is GV decide to add the "Mark as Read" feature to the notification, so we don't have to find our own way out! Hope this answers your question, but do let me know for anything!

**Comment by mario0318** [comment]
That was a highly informative and detailed response. So just to get a solid take here of what was done...

You took the bundle from android.auto which had an internal or "muted" method of marking messages as read once it was played or open or however Android Auto displays it, and you then created a UI element for the GV notification window to display an interaction labeled "Mark as Read" which you then simply linked to the android.auto bundle which then signals GV to do its thing and mark the message as read. Is that about right? In other words, the actual mechanism by which GV marks the message as read is still unknown unless we peek further inside the apk itself? 

Thank you again!

**Comment by zehuanli** [comment]
Sorry I didn't see your comment has been edited with questions.

Yes, we create a standard notification action (button) and utilize the method provided by GV to mark a particular message as read. I believe (but didn't investigate further on) that the method is actually being actively used by Android Auto. Once in the future if this is made unavailable, we need to dig further into the apk and implement our functions to mark a message as read.
